### PR TITLE
feat(package): remove dependency on ext-intl

### LINKED ISSUE #7: Get rid of the intl extension requirement
I use this library inside a symfony project where intl is not required because symfony give a polyfill for it. 

Currently its not possible to use this library without intl installed (composer will error). I would recommend to use the symfony intl polyfill https://github.com/symfony/polyfill-intl-icu instead of require `ext-intl`.

```json
"symfony/polyfill-intl-icu": "^1.0",
```

### PR DESCRIPTION
**Pull request by alexander-schranz**
fixes #7

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@layershifter dont know why the scrutinizer-ci errors

**Comment by layershifter** [comment]
@alexander-schranz Thanks for PR!

I'm glad to use Symfony's polyfill, but it doesn't provide `idn_to_utf8` function. Test build's result in this PR isn't correct because `intl` is enabled by default in [envirioment](https://docs.travis-ci.com/user/ci-environment/#Extensions) and it cannot be [removed](https://github.com/travis-ci/travis-ci/issues/4701) :slightly_frowning_face: 

----

According to PHP docs `idn_to_utf8` uses IDNA 2003 for transforms and we can try to use [true/php-punycode](https://github.com/true/php-punycode), but it will require [`ext-mbstring`](https://github.com/true/php-punycode/blob/master/composer.json#L20) :-1: 

So, here is TODO list for removing `ext-intl` dependency:
* [ ] move builds to Docker;
* [ ] create and accept PR for removing `ext-mbstring` dependency from `true/php-punycode`;
* [ ] make simple wrapper around `idn_to_utf8`.

Looks little complicated :smile: I'll start to work on it today.

**Comment by alexander-schranz** [comment]
@layershifter create thank you. mbstring can also be used from symfony: https://github.com/symfony/polyfill-mbstring

**Comment by Marlinc** [comment]
We've made a new release of true/php-punycode in which symfony/polyfill-mbstring can be used

**Comment by alexander-schranz** [comment]
thank you @Marlinc

**Comment by layershifter** [comment]
Two steps completed, let's complete last 😄 

I think it's not good idea to send `idn_to_utf8` and `idn_to_ascii` functions into global. Our implementation isn't real polyfill and it's can cause conflicts with other package.

Let's make a small refactoring there, it will give following advantages:
* `function_exists` will called once;
* `Punycode` object will be created once.

#### Extract.php

```diff
    /**
     * @var int Value of extraction options.
     */
    private $extractionMode;
+   /**
+    * @var IDN Object of TLDExtract\IDN class.
+    */
+   private $idn;
    /**
     * @var string Name of class that will store results of parsing.
     */
    private $resultClassName;
```

```diff
        public function __construct($databaseFile = null, $resultClassName = null, $extractionMode = null)
    {
+       $this->idn = new IDN();
        $this->suffixStore = new Store($databaseFile);
```

```diff
        if ($isPunycoded) {
-             $hostname = idn_to_utf8($hostname);
+            $hostname = $this->idn->toUTF8($hostname);
        }
```

```diff
-        return $isPunycoded ? idn_to_ascii($suffix) : $suffix;
+        return $isPunycoded ? $this->idn->toASCII($hostname) : $suffix;
```

#### IDN.php

```php
<?php

namespace LayerShifter\TLDExtract;

use TrueBV\Punycode;

/**
 * Class that transforms IDN domains, if `intl` extension present uses it.
 */
class IDN
{

    /**
     * @var Punycode Object of TrueBV\Punycode class.
     */
    private $transformer;

    /**
     * Constructor.
     */
    public function __construct()
    {
        if (!function_exists('\idn_to_utf8')) {
            $this->transformer = new Punycode();
        }
    }

    /**
     * Converts domain name from Unicode to IDNA ASCII.
     *
     * @param string $domain Domain to convert in IDNA ASCII-compatible format.
     *
     * @return string
     */
    public function toASCII($domain)
    {
        if ($this->transformer) {
            return $this->transformer->encode($domain);
        }

        return idn_to_ascii($domain);
    }

    /**
     * Converts domain name from IDNA ASCII to Unicode.
     *
     * @param string $domain Domain to convert in Unicode format.
     *
     * @return string
     */
    public function toUTF8($domain)
    {
        if ($this->transformer) {
            return $this->transformer->decode($domain);
        }

        return idn_to_utf8($domain);
    }
}
```

#### IDNTest.php

```php
<?php

namespace LayerShifter\TLDExtract\Tests;

use LayerShifter\TLDExtract\IDN;
use TrueBV\Punycode;

/**
 * Tests for IDN class.
 */
class IDNTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var IDN Object for tests
     */
    private $idn;

    /**
     * Method that setups test's environment.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->idn = new IDN();
    }

    /**
     * Tests constructor(), ensures that transformer isn't loaded when `intl` extension present.
     *
     * @void
     */
    public function testConstructor()
    {
        if (function_exists('\idn_to_utf8')) {
            $this->assertAttributeInternalType('null', 'transformer', $this->idn);

            return;
        }

        $this->assertAttributeInstanceOf(Punycode::class, 'transformer', $this->idn);
    }

    /**
     * Tests toASCII() method.
     *
     * @return void
     */
    public function testToASCII()
    {
        $this->assertEquals('xn--tst-qla.de', $this->idn->toASCII('täst.de'));
    }

    /**
     * Tests toUTF8() method.
     *
     * @return void
     */
    public function testToUTF8()
    {
        $this->assertEquals('täst.de', $this->idn->toUTF8('xn--tst-qla.de'));
    }
}

```

**Comment by layershifter** [comment]
@alexander-schranz Thanks much, I'll merge it and prepare release :+1:

**Comment by alexander-schranz** [comment]
@layershifter that was to early 🙈

**Comment by layershifter** [comment]
Yep, I saw that CI tests are failed, will fix it before release :monkey_face:

**Pull request merged**
